src/Entity/Article.php
<?php

namespace App\Entity;

use App\Repository\ArticleRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;


#[ORM\Entity(repositoryClass: ArticleRepository::class)]
#[UniqueEntity('titre', "il existe déjà un article possédant ce titre")]

class Article
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]

    private ?int $id = null;

    #[ORM\Column(length: 200)]

    #[Assert\NotBlank]
    #[Assert\Length(min: 5 ,minMessage: "Le titre doit comporter au moins 5 caractères")]



    private ?string $titre = null;


    #[ORM\Column(type: Types::TEXT)]
    private ?string $contenu = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $createdAt = null;

    #[ORM\Column(length: 255)]
    private ?string $slug = null;

    #[ORM\ManyToOne(inversedBy: 'articles')]
    private ?Categorie $categorie = null;

    #[ORM\OneToMany(mappedBy: 'article_id', targetEntity: Commentaire::class)]
    private Collection $commentaires;

    #[ORM\Column]
    private ?bool $isPublie = null;

    public function __construct()
    {
        $this->commentaires = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getContenu(): ?string
    {
        return $this->contenu;
    }

    public function setContenu(string $contenu): self
    {
        $this->contenu = $contenu;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getCategorie(): ?Categorie
    {
        return $this->categorie;
    }

    public function setCategorie(?Categorie $categorie): self
    {
        $this->categorie = $categorie;

        return $this;
    }

    /**
     * @return Collection<int, Commentaire>
     */
    public function getCommentaires(): Collection
    {
        return $this->commentaires;
    }

    public function addCommentaire(Commentaire $commentaire): self
    {
        if (!$this->commentaires->contains($commentaire)) {
            $this->commentaires->add($commentaire);
            $commentaire->setArticleId($this);
        }

        return $this;
    }

    public function removeCommentaire(Commentaire $commentaire): self
    {
        if ($this->commentaires->removeElement($commentaire)) {
            // set the owning side to null (unless already changed)
            if ($commentaire->getArticleId() === $this) {
                $commentaire->setArticleId(null);
            }
        }

        return $this;
    }

    public function isIsPublie(): ?bool
    {
        return $this->isPublie;
    }

    public function setIsPublie(bool $isPublie): self
    {
        $this->isPublie = $isPublie;

        return $this;
    }
}

src/Entity/Commentaire.php
<?php

namespace App\Entity;

use App\Repository\CommentaireRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CommentaireRepository::class)]
class Commentaire
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $contenu = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $createAt = null;

    #[ORM\ManyToOne(inversedBy: 'commentaires')]
    private ?Utilisateur $utilisateur_id = null;

    #[ORM\ManyToOne(inversedBy: 'commentaires')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Article $article_id = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getContenu(): ?string
    {
        return $this->contenu;
    }

    public function setContenu(string $contenu): self
    {
        $this->contenu = $contenu;

        return $this;
    }

    public function getCreateAt(): ?\DateTimeInterface
    {
        return $this->createAt;
    }

    public function setCreateAt(\DateTimeInterface $createAt): self
    {
        $this->createAt = $createAt;

        return $this;
    }

    public function getUtilisateurId(): ?Utilisateur
    {
        return $this->utilisateur_id;
    }

    public function setUtilisateurId(?Utilisateur $utilisateur_id): self
    {
        $this->utilisateur_id = $utilisateur_id;

        return $this;
    }

    public function getArticleId(): ?Article
    {
        return $this->article_id;
    }

    public function setArticleId(?Article $article_id): self
    {
        $this->article_id = $article_id;

        return $this;
    }
}

src/Form/ArticleType.php
<?php

namespace App\Form;

use App\Entity\Article;
use App\Entity\Categorie;
use FOS\CKEditorBundle\Form\Type\CKEditorType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\SearchType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ArticleType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('titre',TextType::class)
            ->add('contenu',CKEditorType::class , [
                'config' => [
                    'uiColor' => 'brown'
                ]
            ])
            ->add('categorie',EntityType::class ,[
                'class' => Categorie::class,
                'choice_label' => 'titre',
                'required' => false,
                'placeholder' => 'Aucune catégorie'

            ])
            ->add('isPublie',CheckboxType::class, [
                'required' => false
            ]);


    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Article::class,
        ]);
    }
}

src/Controller/ArticleController.php
<?php

namespace App\Controller;

use App\Entity\Article;
use App\Entity\Commentaire;
use App\Form\ArticleType;
use App\Form\CommentaireType;
use App\Repository\ArticleRepository;
use App\Repository\CommentaireRepository;
use App\Repository\UtilisateurRepository;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\FormError;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\String\Slugger\SluggerInterface;

class ArticleController extends AbstractController
{
    private ArticleRepository $articleRepository;
    private CommentaireRepository $commentaireRepository;
    private UtilisateurRepository $utilisateurRepository;


    //Demander à symfony d'injecter une instance de ArticleRepository
    // à la création du controlleur (instance de ArticleControlleur
    public function __construct(ArticleRepository $articleRepository , CommentaireRepository $commentaireRepository, UtilisateurRepository $utilisateurRepository)
    {
        $this->articleRepository = $articleRepository;
        $this->commentaireRepository = $commentaireRepository;
        $this->utilisateurRepository = $utilisateurRepository;

    }


    #[Route('/articles', name: 'app_articles')]

    // A l'appel de la méthode symfony va créer un objet de la classe ArticleRepossitory
    // et le passer en paramètre de la méthode
    // Mécanisme : INJECTION DE DEPENDANCES
    public function getArticles(PaginatorInterface $paginator , Request $request): Response
    {

        // Récupérer les infos dans la base de données
        // Le controlleur fait appel au Modèle(une classe du modèle)
        // Afin de récupérer la liste des articles
        // $repository = new ArticleRepository();

        //Mise en place de la pagination


        $articles = $paginator->paginate(
            $this->articleRepository->findBy(["isPublie" => true],["createdAt" => "DESC",]), /* query NOT result */
            $request->query->getInt('page', 1), /*page number*/
            10 /*limit per page*/
        );




        return $this->render('article/index.html.twig',[
            "articles" => $articles
        ]);
    }

    #[Route('/articles/{slug}', name: 'app_article_slug')]

    // A l'appel de la méthode symfony va créer un objet de la classe ArticleRepossitory
        // et le passer en paramètre de la méthode
        // Mécanisme : INJECTION DE DEPENDANCES
    public function getArticle($slug , Request $request): Response
    {
        // Récupérer les infos dans la base de données
        // Le controlleur fait appel au Modèle(une classe du modèle)
        // Afin de récupérer la liste des articles
        // $repository = new ArticleRepository();

            $commentaire = new Commentaire();
            $formCommentaire = $this->createForm(CommentaireType::class, $commentaire);
            $formCommentaire->handleRequest($request);
            if ($formCommentaire->isSubmitted() && $formCommentaire->isValid()) {
                $commentaire->setCreateAt(new \Datetime())
                    ->setArticleId($this->articleRepository->findOneBy(["slug" => $slug]))
                    ->setUtilisateurId($this->utilisateurRepository->findOneBy(['pseudo' => $formCommentaire->get('pseudo')->addError(new FormError("Pseudo inexistant"))->getData()]));
                $this->commentaireRepository->add($commentaire,true);
            }
            return $this->renderForm('article/article.html.twig', [
                    'formCommentaire' => $formCommentaire,
                    "article" => $this->articleRepository->findOneBy(["slug" => $slug]),
                    "commentaires" => $this->commentaireRepository->findBy(["article_id" => $this->articleRepository->findBy(["slug" => $slug])])
                ]
            );
    }



    #[Route('/articles/nouveau', name: 'app_articles_nouveau', methods: ['GET' , 'POST'] , priority: 1)]

    // A l'appel de la méthode symfony va créer un objet de la classe ArticleRepossitory
        // et le passer en paramètre de la méthode
        // Mécanisme : INJECTION DE DEPENDANCES
    public function insert(SluggerInterface $slugger, Request $request): Response
    {
        $article = new Article();
        // Création du formulaire
        $formArticle = $this->createForm(ArticleType::class,$article);

        // Reconnaître si le formulaire a été soumis ou pas
        $formArticle->handleRequest($request);
        // Est-ce que le formulaire a été soumis
        if ($formArticle->isSubmitted() && $formArticle->isValid()){
            $article->setSlug($slugger->slug($article->getTitre())->lower())
                    ->setCreatedAt(new \Datetime());

            $this->articleRepository->add($article,true);
            return $this->redirectToRoute("app_articles");
        }

        // Appel de le vue twig permettant d'afficher le formulaire
        return $this->renderForm('article/nouveau.html.twig',[
            'formArticle' => $formArticle
            ]
        );

        /*$article->setTitre('Nouvel article 2')
            ->setContenu("Contenu du nouvel article 2")
            ->setSlug($slugger->slug($article->getTitre())->lower())
            ->setCreatedAt(new \DateTime());

        // Propre à symfony 6
        $this->aricleRepository->add($article,true);

        return $this->redirectToRoute("app_articles");
        */
    }


    #[Route('/articles/modifie:{slug}', name: 'app_articles_modifie_slug', methods: ['GET' , 'POST'] , priority: 1)]

    // A l'appel de la méthode symfony va créer un objet de la classe ArticleRepossitory
        // et le passer en paramètre de la méthode
        // Mécanisme : INJECTION DE DEPENDANCES
    public function update(SluggerInterface $slugger, Request $request,$slug): Response
    {
        $article = $this->articleRepository->findOneBy(["slug" => $slug]);
        // Création du formulaire
        $formArticle = $this->createForm(ArticleType::class, $article);

        // Reconnaître si le formulaire a été soumis ou pas
        $formArticle->handleRequest($request);
        // Est-ce que le formulaire a été soumis
        if ($formArticle->isSubmitted() && $formArticle->isValid()) {
            $article->setSlug($slugger->slug($article->getTitre())->lower());


            $this->articleRepository->add($article, true);
            return $this->redirectToRoute("app_articles");
        }

        // Appel de le vue twig permettant d'afficher le formulaire
        return $this->renderForm('article/update.html.twig', [
                'formArticle' => $formArticle,
                'article' => $article
            ]
        );
    }

}

templates/article/article.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des Articles{% endblock %}

{% block body %}
    <h1 class="mt-3 mb-4">Détail article</h1>
    <div class="  mb-5">
        <h5 class=""> <b>{{ article.titre }} </b> {{ article.createdAt | date("d/m/Y")  }}</h5>
        {% if article.categorie is not null %}
        <h6 class=" "><a class="btn btn-secondary" href="{{ path("app_categorie_slug" , {slug : article.categorie.slug })}}">{{ article.categorie.titre }}</a></h6>
        {% else %}
        <h6> Aucune catégorie </h6>
        {% endif %}
        <p class="">{{ article.contenu | raw }} </p>

        <h6 class=" "><a class="btn btn-secondary" href="{{ path("app_articles_modifie_slug" , {slug : article.slug })}}">Modifier article</a></h6>
    </div>

    {% if article.commentaires.count >1 %}
    <h3 class="mb-3">{{ article.commentaires.count}} Commentaires</h3>

    {% elseif article.commentaires.count == 0 %}
        <h3 class="mb-3">Aucun commentaire</h3>

    {% else %}
    <h3 class="mb-3">{{ article.commentaires.count}} Commentaire</h3>
    {% endif %}

    <h4>Ajout d'un commentaire</h4>

    {{ form_start(formCommentaire) }}

    {{ form_label(formCommentaire.pseudo,"Pseudo utilisateur")}}
    {{ form_widget(formCommentaire.pseudo, {
        'attr' : {
            'placeholder' : "Saisir votre pseudo"
        },
    })}}


    {{ form_label(formCommentaire.contenu,"Contenu de l'article")}}

    {{ form_widget(formCommentaire.contenu, {
        'attr' : {
            'placeholder' : "Veuillez saisir un contenu"
        },
    })}}




    <input type="submit" class="btn btn-primary mt-3" value="ajouter">

    {{ form_end(formCommentaire) }}

    <div class="">
        {% for commentaire in commentaires %}
            <ul>
            {%if commentaire.utilisateurId %}
            <li><h5><b>{{ commentaire.utilisateurId.pseudo }} </b>{{ commentaire.createAt | date("d/m/Y") }}</h5></li>
            {%else %}
            <li><h5> <b>Anonyme {{ commentaire.createAt | date("d/m/Y") }}</b></h5></li>
            {% endif %}
            <p class="mb-3">{{ commentaire.contenu }}</p>
            </ul>
        {% endfor %}
    </div>



{% endblock %}

templates/article/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des Articles{% endblock %}

{% block body %}



    <h1>Liste de tous les articles</h1>
    <a class="btn btn-primary mb-3" href="{{ path('app_articles_nouveau') }}">Créer un article</a>
    <ul>
        {% for article in articles %}
            <li>{{ article.titre }} <a href="{{ path('app_article_slug',{slug : article.slug}) }}">plus d'info </a></li>
        {% endfor %}

    </ul>


    <div class="navigation d-flex justify-content-center">
        {{ knp_pagination_render(articles) }}
    </div>
{% endblock %}

templates/article/nouveau.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nouvel Article{% endblock %}


{% block body %}
<h1>Création d'un article</h1>
    {{ form_start(formArticle) }}
    {{ form_row(formArticle.titre, {
        'label' : 'titre article',
        'attr' : {
            'placeholder' : "Veuillez saisir le titre de l'article"
        },
        'help' : "le titre doit contenir au moins 5 caractères"
    }) }}

    {{ form_label(formArticle.contenu,"Contenu de l'article" , {
        'label_attr' : {
            'class' : 'text-warning'
        }
    })}}

    {{ form_widget(formArticle.contenu, {
        'attr' : {
            'placeholder' : "Veuillez saisir un contenu"
        },
    })}}
    {{ form_help(formArticle.contenu , {
        'help' : "le contenu doit contenir au mois 36 caractères"
    }) }}
    {{ form_row(formArticle.categorie) }}
    {{ form_row(formArticle.isPublie ,{
        'label' : "publié l'article"
        })
    }}

    <input type="submit" class="btn btn-primary mt-3" value="ajouter">

    {{ form_end(formArticle) }}


{% endblock %}

templates/article/update.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier Article{% endblock %}


{% block body %}
    <h1>Modification d'un article</h1>
    {{ form_start(formArticle) }}
    {{ form_row(formArticle.titre, {
        'label' : 'titre article',
        'attr' : {
            'placeholder' : "Veuillez saisir le titre de l'article"
        },
        'help' : "le titre doit contenir au moins 5 caractères"
    }) }}

    {{ form_label(formArticle.contenu,"Contenu de l'article" , {
        'label_attr' : {
            'class' : 'text-warning'
        }
    })}}

    {{ form_widget(formArticle.contenu, {
        'attr' : {
            'placeholder' : "Veuillez saisir un contenu"
        },
    })}}
    {{ form_help(formArticle.contenu , {
        'help' : "le contenu doit contenir au mois 36 caractères"
    }) }}
    {{ form_row(formArticle.categorie) }}
    {{ form_row(formArticle.isPublie ,{
        'label' : "publié l'article"
    })
    }}

    <input type="submit" class="btn btn-primary mt-3" value="modifier">

    {{ form_end(formArticle) }}


{% endblock %}